/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;

import java.sql.Date;
import java.util.Scanner;




public class App {


  public static void main(String[] args) {


    final int LENGTH = 10;
    int num = 0;
    
    int[] no = new int[LENGTH];
    String[] name = new String[LENGTH];
    String[] email = new String[LENGTH];
    String[] password = new String[LENGTH];
    String[] photo = new String[LENGTH];
    String[] tel = new String[LENGTH];
    Date registeredDate = new Date(System.currentTimeMillis());
    
    
    Scanner keyIn = new Scanner(System.in);

    
      while(true) {
    
      try {
		
	
      System.out.print("번호?");
      no[num] = Integer.parseInt( keyIn.nextLine() );

      System.out.print("이름?");
      name[num] = keyIn.nextLine();      
      
     
      System.out.print("이메일?");
      email[num] = keyIn.nextLine();
  
      System.out.print("암호?");
      password[num] = keyIn.nextLine();

      System.out.print("사진?");
      photo[num] = keyIn.nextLine();

      System.out.print("전화?");
      tel[num] = keyIn.nextLine();
      
      } catch (Exception e) {
  	    System.out.println(" ");  
      }
     
     System.out.println("계속 입력하시겠습니까?(Y/n)");
     String str = keyIn.nextLine();
    
     if(!str.equalsIgnoreCase("y") || str.length()<0) 
               break;  	 
     
       
     num++;
    }
   
    keyIn.close();

			    for(int i =0 ; i < num; i++) {
			
			      System.out.printf("%d, %s , %s      , %s      ,  %s ", 
			         no[i],  name[i], email[i],  tel[i], registeredDate 
			          );
			
			    }

  }
  
}
