/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;

import java.sql.Date;
import java.util.Scanner;



public class App {


  public static void main(String[] args) {


	     /*  nextLint은 개행문자를 포함애서 읽어 들이구요.  nextInt는 개행문자까지의 int형 데이터를 읽어들려서 그래요.

      그러니까 nextInt에서 5000을 넣고 엔터를 치면 5000까지 읽고 버퍼에는 개행문자가 들어가 있죠.

 

       그러면 다음에 nextLine을 만나면 버퍼에 있는 개행문자를 읽어 들여요. 그래서 두번째커피는: 과 금액이 같이 출력 되는 거예요.

       실제로는 개행문자가 읽어진거죠. */
    final int DEFAULT_SIZE = 1;


    int[] no = new int[DEFAULT_SIZE] ;    
    String [] name = new String[DEFAULT_SIZE];
    String [] email = new String[DEFAULT_SIZE];
    int [] secret = new int[DEFAULT_SIZE];
    String [] photo = new String[DEFAULT_SIZE];
    String [] phone = new String[DEFAULT_SIZE];
    Date joinDay = new Date(System.currentTimeMillis());
    Date[] j2 = new Date[1]; 
    
    j2[0] = Date.valueOf(new String("2222-03-22")); 

    Scanner keyIn = new Scanner(System.in);

    for(int i =0 ; i < DEFAULT_SIZE ; i++ ) {

      System.out.print("번호?");
      no[i] = Integer.parseInt( keyIn.nextLine() );

      System.out.print("이름?");
      name[i] = keyIn.nextLine();      
      
     
      System.out.print("이메일?");
      email[i] = keyIn.nextLine();
  
      System.out.print("암호?");
      secret[i] = Integer.parseInt(keyIn.nextLine());

      System.out.print("사진?");
      photo[i] = keyIn.nextLine();

      System.out.print("전화?");
      phone[i] = keyIn.nextLine();


    }
   
    keyIn.close();

			    for(int i =0 ; i < DEFAULT_SIZE; i++) {
			
			      System.out.printf("번호 %d\n이름%s\n이메일%s\n암호%d\n사진%s\n전화%s\n가입일%s ", 
			         no[i],  name[i], email[i], secret[i], photo[i], phone[i], joinDay
			          );
			
			    }

  }
  
}
