/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;
import java.sql.Date;
import java.util.Scanner;



public class App {


  public static void main(String[] args) {


    /*  목록으로 출력할 항목은 번호,수업명,시작일~종료일,총수업시간이다.  
     *      계속 입력하시겠습니까?(Y/n) n

        1, 자바 프로젝트 실습     , 2019-01-02 ~ 2019-05-28, 1000
        2, 자바 프로그래밍 기초    , 2019-02-01 ~ 2019-02-28,  160
        3, 자바 프로그래밍 고급    , 2019-03-02 ~ 2019-03-30,  160*/
    final int DEFAULT_SIZE = 20;


    int[] no = new int[DEFAULT_SIZE] ;    
    String [] title = new String[DEFAULT_SIZE];
    String [] contents = new String[DEFAULT_SIZE];
    Date[] startDate = new Date[DEFAULT_SIZE];
    Date[] endDate = new Date[DEFAULT_SIZE];
    int [] totlaHours = new int[DEFAULT_SIZE];
    int [] dayHours = new int[DEFAULT_SIZE];

    int len = 0 ;



    Scanner keyIn = new Scanner(System.in);

    for(int i =0 ; i <DEFAULT_SIZE ; i++ ) {

      System.out.print("번호?");
      no[i] = keyIn.nextInt();

      System.out.print("수험명?");
      title[i] = keyIn.nextLine();

      System.out.print("내용?");
      contents[i] = keyIn.nextLine();

      System.out.print("강의시작일?");
      startDate[i] = Date.valueOf(keyIn.nextLine());
  
      System.out.print("총강의시간?");
      totlaHours[i] = keyIn.nextInt();

      System.out.print("일강의시간?");
      endDate[i] = Date.valueOf(keyIn.nextLine());

      System.out.print("번호?");
      dayHours[i] = Integer.parseInt(keyIn.nextLine());

      len++;

      System.out.print("계속 입력하시겠습니까?(Y/n)");
      String input = keyIn.nextLine();
      if(input.equals("") || input.equalsIgnoreCase("y")) {
        continue;
      }
      break;
    }

    keyIn.close();

    for(int i =0 ; i < len; i++) {

      System.out.printf("%d, %s %s ~ %s, %d \n", 
          no[i],  title[i], contents[i], startDate[i],endDate[i],totlaHours[i],dayHours[i]
          );

    }

  }
}
