/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;

public class App {
    

    public static void main(String[] args) {
        System.out.println("hello");
        System.out.println("world");
      
    }
}
